[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  timeout = 40

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200